### ISSUE TITLE
License and Copyright

### ISSUE THREAD

**Issue by germonprez** [Nebrethar/Web-Extensions-Nebrethar#1]
@Nebrethar could you include license and copyright information as needed on the files you have? I don't see any such declarations, making it a bit difficult to know what is yours and what is from somewhere else.

**Comment by Nebrethar** [comment]
@germonprez Thanks for your concern. I published a wiki page that identifies the sources for code in each project, and a link used for each set of images and how they were modified.

**Comment by germonprez** [comment]
@Nebrethar I would recommend you get this information into the README. Wiki pages on GH are a bit of a ghost town.

**Comment by Nebrethar** [comment]
@germonprez Thanks for the advice. The information is up and readable on the README.

**Comment by germonprez** [comment]
Thanks!
